import { ElementTypeInfo } from "../types.js";

export function listElementTypes(): ElementTypeInfo[] {
  return [
    {
      type: "line",
      description: "A straight line between two points. Rendered with hand-drawn wobble.",
      properties: [
        { name: "x1", type: "number", required: true, description: "Start X coordinate" },
        { name: "y1", type: "number", required: true, description: "Start Y coordinate" },
        { name: "x2", type: "number", required: true, description: "End X coordinate" },
        { name: "y2", type: "number", required: true, description: "End Y coordinate" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex). Defaults to ink color." },
        { name: "strokeWidth", type: "number", required: false, description: "Line thickness in pixels" },
      ],
      example: { type: "line", x1: 50, y1: 50, x2: 200, y2: 50, color: "#222" },
    },
    {
      type: "rect",
      description: "A rectangle defined by top-left corner and dimensions. Drawn as four wobble lines.",
      properties: [
        { name: "x", type: "number", required: true, description: "Top-left X coordinate" },
        { name: "y", type: "number", required: true, description: "Top-left Y coordinate" },
        { name: "w", type: "number", required: true, description: "Width" },
        { name: "h", type: "number", required: true, description: "Height" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
        { name: "strokeWidth", type: "number", required: false, description: "Line thickness" },
      ],
      example: { type: "rect", x: 100, y: 80, w: 200, h: 120, color: "#111" },
    },
    {
      type: "circle",
      description: "A circle defined by center and radius. Rendered with wobble for hand-drawn feel.",
      properties: [
        { name: "cx", type: "number", required: true, description: "Center X coordinate" },
        { name: "cy", type: "number", required: true, description: "Center Y coordinate" },
        { name: "r", type: "number", required: true, description: "Radius" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
        { name: "strokeWidth", type: "number", required: false, description: "Line thickness" },
      ],
      example: { type: "circle", cx: 200, cy: 200, r: 50, color: "#333" },
    },
    {
      type: "arc",
      description: "An arc (partial circle) defined by center, radius, and angle range in degrees.",
      properties: [
        { name: "cx", type: "number", required: true, description: "Center X coordinate" },
        { name: "cy", type: "number", required: true, description: "Center Y coordinate" },
        { name: "r", type: "number", required: true, description: "Radius" },
        { name: "startAngle", type: "number", required: true, description: "Start angle in degrees" },
        { name: "endAngle", type: "number", required: true, description: "End angle in degrees" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "arc", cx: 200, cy: 200, r: 60, startAngle: 0, endAngle: 90, color: "#333" },
    },
    {
      type: "arrow",
      description: "A line with an arrowhead at the end point. Useful for flow diagrams.",
      properties: [
        { name: "x1", type: "number", required: true, description: "Start X coordinate" },
        { name: "y1", type: "number", required: true, description: "Start Y coordinate" },
        { name: "x2", type: "number", required: true, description: "End X coordinate (arrowhead)" },
        { name: "y2", type: "number", required: true, description: "End Y coordinate (arrowhead)" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "arrow", x1: 100, y1: 150, x2: 250, y2: 150, color: "#111" },
    },
    {
      type: "text",
      description: "Hand-written style text using the Caveat font. Slightly rotated for organic feel.",
      properties: [
        { name: "x", type: "number", required: true, description: "X coordinate" },
        { name: "y", type: "number", required: true, description: "Y coordinate (baseline)" },
        { name: "text", type: "string", required: true, description: "Text content" },
        { name: "fontSize", type: "number", required: false, description: "Font size in pixels. Default: 14" },
        { name: "color", type: "string", required: false, description: "Text color (hex)" },
      ],
      example: { type: "text", x: 100, y: 100, text: "Hello World", fontSize: 20, color: "#111" },
    },
    {
      type: "dashed",
      description: "A dashed line between two points. Each dash segment has its own wobble.",
      properties: [
        { name: "x1", type: "number", required: true, description: "Start X coordinate" },
        { name: "y1", type: "number", required: true, description: "Start Y coordinate" },
        { name: "x2", type: "number", required: true, description: "End X coordinate" },
        { name: "y2", type: "number", required: true, description: "End Y coordinate" },
        { name: "dashLength", type: "number", required: false, description: "Dash length in pixels. Default: 8" },
        { name: "gapLength", type: "number", required: false, description: "Gap length in pixels. Default: 6" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "dashed", x1: 50, y1: 250, x2: 650, y2: 250, color: "#999" },
    },
    {
      type: "dim",
      description: "A dimension line with arrows at both ends, extension lines, and a measurement label. Used for showing distances in floor plans.",
      properties: [
        { name: "x1", type: "number", required: true, description: "Start X coordinate" },
        { name: "y1", type: "number", required: true, description: "Start Y coordinate" },
        { name: "x2", type: "number", required: true, description: "End X coordinate" },
        { name: "y2", type: "number", required: true, description: "End Y coordinate" },
        { name: "label", type: "string", required: true, description: "Measurement text (e.g. '5.0 m')" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "dim", x1: 50, y1: 30, x2: 850, y2: 30, label: "16.0 m", color: "#8B4513" },
    },
    {
      type: "window",
      description: "A window symbol: a line with perpendicular tick marks. Used on walls in floor plans.",
      properties: [
        { name: "x1", type: "number", required: true, description: "Start X coordinate" },
        { name: "y1", type: "number", required: true, description: "Start Y coordinate" },
        { name: "x2", type: "number", required: true, description: "End X coordinate" },
        { name: "y2", type: "number", required: true, description: "End Y coordinate" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "window", x1: 120, y1: 50, x2: 280, y2: 50, color: "#336" },
    },
    {
      type: "door-symbol",
      description: "A swing door symbol with hinge point and arc showing the door swing path.",
      properties: [
        { name: "x", type: "number", required: true, description: "X coordinate of the door start" },
        { name: "y", type: "number", required: true, description: "Y coordinate (on the wall line)" },
        { name: "w", type: "number", required: true, description: "Door width" },
        { name: "swing", type: "'left' | 'right'", required: false, description: "Swing direction. Default: 'left'" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "door-symbol", x: 290, y: 320, w: 60, swing: "left", color: "#8B4513" },
    },
    {
      type: "door-slide",
      description: "A sliding door symbol with two parallel lines and a direction arrow.",
      properties: [
        { name: "x", type: "number", required: true, description: "X coordinate" },
        { name: "y", type: "number", required: true, description: "Y coordinate" },
        { name: "w", type: "number", required: true, description: "Door width" },
        { name: "direction", type: "'left' | 'right'", required: false, description: "Slide direction. Default: 'right'" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "door-slide", x: 200, y: 300, w: 80, direction: "right", color: "#8B4513" },
    },
    {
      type: "stair",
      description: "A staircase symbol: a rectangle divided by horizontal tread lines.",
      properties: [
        { name: "x", type: "number", required: true, description: "Top-left X coordinate" },
        { name: "y", type: "number", required: true, description: "Top-left Y coordinate" },
        { name: "w", type: "number", required: true, description: "Width" },
        { name: "h", type: "number", required: true, description: "Height" },
        { name: "steps", type: "number", required: false, description: "Number of steps. Default: 8" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "stair", x: 620, y: 80, w: 60, h: 140, steps: 10, color: "#888" },
    },
    {
      type: "opening",
      description: "A wall opening (no door) shown as a gap with small perpendicular returns at each end.",
      properties: [
        { name: "x1", type: "number", required: true, description: "Start X coordinate" },
        { name: "y1", type: "number", required: true, description: "Start Y coordinate" },
        { name: "x2", type: "number", required: true, description: "End X coordinate" },
        { name: "y2", type: "number", required: true, description: "End Y coordinate" },
        { name: "color", type: "string", required: false, description: "Stroke color (hex)" },
      ],
      example: { type: "opening", x1: 300, y1: 200, x2: 380, y2: 200, color: "#222" },
    },
    {
      type: "column",
      description: "A structural column shown as a filled circle. Used in floor plans.",
      properties: [
        { name: "cx", type: "number", required: true, description: "Center X coordinate" },
        { name: "cy", type: "number", required: true, description: "Center Y coordinate" },
        { name: "size", type: "number", required: false, description: "Column diameter. Default: 10" },
        { name: "color", type: "string", required: false, description: "Fill/stroke color (hex)" },
      ],
      example: { type: "column", cx: 300, cy: 500, size: 12, color: "#444" },
    },
  ];
}
